### ISSUE TITLE
Implementation of Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by thevijayshankersharma** [Sahil1786/Petari#88] opened 2024-05-16 13:25 UTC
Is your feature request related to a problem? Please describe.
Currently, the absence of a dark/light mode toggle limits user customization options and may lead to discomfort during prolonged usage, especially in low-light environments.

Describe the solution you'd like
I would like to implement a toggle switch within the application interface, allowing users to seamlessly switch between dark and light modes. Dark mode should feature darker color schemes for improved readability and reduced eye strain.

Describe alternatives you've considered
An alternative approach could involve providing predefined themes with dark and light mode options. However, a toggle switch offers a more intuitive and user-friendly solution.

Additional context
The addition of a dark/light mode toggle aligns with modern design trends and user preferences for customizable interfaces. It enhances user satisfaction and usability by providing a personalized browsing experience tailored to individual preferences.

**Comment by Pranali3103** [comment] 2024-05-23 12:53
@Sahil1786 , if this issue is open can you please assign this to me.

**Comment by Twisha-coder** [comment] 2024-05-27 13:52
@Sahil1786 ,please assign this task to me if the issue is opened

**Comment by heli0707** [comment] 2024-06-22 05:55
@Sahil1786 Please assign this issue to me. I am eager to work on it and will complete it.

**Closed** 2024-06-22 14:15 UTC
Labels: GSSOC'2024, level2, gssoc
